export const GET_HELLO_WORLD = 'GET_HELLO_WORLD';
export const GET_EXAMPLES = 'GET_EXAMPLES';
export const ADD_WITNESS = 'ADD_WITNESS';
export const REMOVE_WITNESS = 'REMOVE_WITNESS';
export const ADD_CRIMINAL = 'ADD_CRIMINAL';
export const REMOVE_CRIMINAL = 'REMOVE_CRIMINAL';
